import "./App.css";
import Search from "./Components/Search";

const App = () => {
  const clothesData = [
    "Men's T-Shirt",
    "Women's Blouse",
    "Men's Polo Shirt",
    "Women's Dress",
    "Men's Jeans",
    "Women's Skinny Jeans",
    "Men's Chinos",
    "Women's Leggings",
    "Men's Hoodie",
    "Women's Cardigan",
    "Men's Jacket",
    "Women's Coat",
    "Men's Sweater",
    "Women's Sweater",
    "Men's Sweatshirt",
    "Women's Sweatshirt",
    "Men's Shorts",
    "Women's Shorts",
    "Men's Swim Trunks",
    "Women's Swimsuit",
    "Men's Formal Shirt",
    "Women's Silk Blouse",
    "Men's Suit",
    "Women's Suit",
    "Men's Tie",
    "Women's Scarf",
    "Men's Socks",
    "Women's Socks",
    "Men's Underwear",
    "Women's Underwear",
    "Men's Boxers",
    "Women's Bras",
    "Men's Pajamas",
    "Women's Pajamas",
    "Men's Robe",
    "Women's Robe",
    "Men's Sneakers",
    "Women's Sneakers",
    "Men's Dress Shoes",
    "Women's High Heels",
    "Men's Boots",
    "Women's Ankle Boots",
    "Men's Sandals",
    "Women's Sandals",
    "Men's Flip Flops",
    "Women's Flip Flops",
    "Men's Belt",
    "Women's Belt",
    "Men's Watch",
    "Women's Watch",
    "Men's Sunglasses",
    "Women's Sunglasses",
    "Men's Baseball Cap",
    "Women's Sun Hat",
    "Men's Beanie",
    "Women's Beret",
    "Men's Gloves",
    "Women's Gloves",
    "Men's Backpack",
    "Women's Handbag",
    "Men's Wallet",
    "Women's Wallet",
    "Men's Messenger Bag",
    "Women's Tote Bag",
    "Men's Briefcase",
    "Women's Clutch",
    "Men's Dress Pants",
    "Women's Dress Pants",
    "Men's Cargo Pants",
    "Women's Cargo Pants",
    "Men's Denim Jacket",
    "Women's Denim Jacket",
    "Men's Bomber Jacket",
    "Women's Bomber Jacket",
    "Men's Windbreaker",
    "Women's Windbreaker",
    "Men's Raincoat",
    "Women's Raincoat",
    "Men's Winter Coat",
    "Women's Winter Coat",
    "Men's Down Jacket",
    "Women's Down Jacket",
    "Men's Puffer Jacket",
    "Women's Puffer Jacket",
    "Men's Leather Jacket",
    "Women's Leather Jacket",
    "Men's Tracksuit",
    "Women's Tracksuit",
    "Men's Sports Shorts",
    "Women's Sports Shorts",
    "Men's Sports Bra",
    "Women's Sports Bra",
    "Men's Sports Leggings",
    "Women's Sports Leggings",
    "Men's Running Shoes",
    "Women's Running Shoes",
    "Men's Training Shoes",
    "Women's Training Shoes",
    "Men's Yoga Pants",
    "Women's Yoga Pants",
    "T-Shirt",
    "Blouse",
    "Polo Shirt",
    "Dress",
    "Jeans",
    "Skinny Jeans",
    "Chinos",
    "Leggings",
    "Hoodie",
    "Cardigan",
    "Jacket",
    "Coat",
    "Sweater",
    "Sweatshirt",
    "Shorts",
    "Swim Trunks",
    "Swimsuit",
    "Formal Shirt",
    "Silk Blouse",
    "Suit",
    "Tie",
    "Scarf",
    "Socks",
    "Underwear",
    "Boxers",
    "Bras",
    "Pajamas",
    "Robe",
    "Sneakers",
    "Dress Shoes",
    "Boots",
    "Sandals",
    "Flip Flops",
    "Belt",
    "Watch",
    "Sunglasses",
    "Baseball Cap",
    "Beanie",
    "Gloves",
    "Backpack",
    "Wallet",
    "Messenger Bag",
    "Briefcase",
    "Dress Pants",
    "Cargo Pants",
    "Denim Jacket",
    "Bomber Jacket",
    "Windbreaker",
    "Raincoat",
    "Winter Coat",
    "Down Jacket",
    "Puffer Jacket",
    "Leather Jacket",
    "Tracksuit",
    "Sports Shorts",
    "Sports Bra",
    "Sports Leggings",
    "Running Shoes",
    "Training Shoes",
    "Yoga Pants",
  ];
  return (
    <div className="App">
      <h1>Happy Shopping..</h1>
      <Search clothesData={clothesData} />
    </div>
  );
};

export default App;
